x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  maru:
    hostname: linea-maru
    image: consensys/maru:${MARU_VERSION}
    restart: unless-stopped
    ports:
      - "${MARU_P2P_PORT}:9000/tcp" # P2P main port
      - "${MARU_P2P_PORT}:9000/udp" # P2P discovery port (UDP only)
    environment:
      - JAVA_OPTS=-Xmx2g
    volumes:
      - ./maru/maru-config.toml:/opt/consensys/maru/configs/maru-config.toml:ro
      - ./maru/maru-genesis.json:/opt/consensys/maru/configs/maru-genesis.json:ro
      - ./maru/log4j.xml:/opt/consensys/maru/configs/log4j.xml:ro
      - ./engine-jwt:/opt/consensys/maru/configs/jwt:ro
      - linea-mainnet-maru:/opt/maru
    command:
      - "java"
      - "-Dlog4j2.configurationFile=/opt/consensys/maru/configs/log4j.xml"
      - "-jar"
      - "/opt/consensys/maru/maru.jar"
      - "--maru-genesis-file"
      - "/opt/consensys/maru/configs/maru-genesis.json"
      - "--config"
      - "/opt/consensys/maru/configs/maru-config.toml"
    labels:
      - metrics.scrape=true
      - metrics.port=9090
      - metrics.path=/prometheus
      - metrics.network=linea-${NETWORK}
      - traefik.enable=true
      - traefik.http.routers.${MARU_HOST:-maru}.service=${MARU_HOST:-maru}
      - traefik.http.routers.${MARU_HOST:-maru}.entrypoints=websecure
      - traefik.http.routers.${MARU_HOST:-maru}.rule=Host(`${MARU_HOST:-maru}.${DOMAIN}`)
      - traefik.http.routers.${MARU_HOST:-maru}.tls.certresolver=letsencrypt
      - traefik.http.routers.${MARU_HOST:-maru}lb.service=${MARU_HOST:-maru}
      - traefik.http.routers.${MARU_HOST:-maru}lb.entrypoints=websecure
      - traefik.http.routers.${MARU_HOST:-maru}lb.rule=Host(`${MARU_LB:-maru-lb}.${DOMAIN}`)
      - traefik.http.routers.${MARU_HOST:-maru}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${MARU_HOST:-maru}.loadbalancer.server.port=8080
    <<: *logging

volumes:
  linea-mainnet-maru:
  